apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <%= name %>
  namespace: <%= project.namespace %>
  labels:
    caninemanaged: 'true'
spec:
  secretName: <%= certificate_name %>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  <% service.domains.each do |domain| %>
  - <%= domain.domain_name %>
  <% end %>
