apiVersion: batch/v1
kind: Job
metadata:
  name: <%= name %>
  namespace: <%= project.name %>
  labels:
    caninemanaged: 'true'
    app: <%= project.name %>
    component: predeployment
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: <%= project.name %>
        component: predeployment
    spec:
      restartPolicy: Never
      containers:
      - name: <%= project.name %>
        image: <%= project.container_image_reference %>
        imagePullPolicy: Always
        command: <%= command.split.to_json %>
        envFrom:
        - configMapRef:
            name: <%= project.name %>
        <% if @project.volumes.present? %>
        volumeMounts:
        <% @project.volumes.each do |volume| %>
        - name: <%= volume.name %>
          mountPath: <%= volume.mount_path %>
        <% end %>
        <% end %>
        <% resource_constraint = project.resource_constraint %>
        <% if resource_constraint.present? %>
        resources:
          <% if resource_constraint.cpu_request.present? || resource_constraint.memory_request.present? || resource_constraint.gpu_request.present? %>
          requests:
            <% if resource_constraint.cpu_request.present? %>
            cpu: "<%= resource_constraint.cpu_request_formatted %>"
            <% end %>
            <% if resource_constraint.memory_request.present? %>
            memory: "<%= resource_constraint.memory_request_formatted %>"
            <% end %>
            <% if resource_constraint.gpu_request.present? && resource_constraint.gpu_request > 0 %>
            nvidia.com/gpu: <%= resource_constraint.gpu_request %>
            <% end %>
          <% end %>
          <% if resource_constraint.cpu_limit.present? || resource_constraint.memory_limit.present? %>
          limits:
            <% if resource_constraint.cpu_limit.present? %>
            cpu: "<%= resource_constraint.cpu_limit_formatted %>"
            <% end %>
            <% if resource_constraint.memory_limit.present? %>
            memory: "<%= resource_constraint.memory_limit_formatted %>"
            <% end %>
            <% if resource_constraint.gpu_request.present? && resource_constraint.gpu_request > 0 %>
            nvidia.com/gpu: <%= resource_constraint.gpu_request %>
            <% end %>
          <% end %>
        <% end %>
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      <% if @project.volumes.present? %>
      volumes:
      <% project.volumes.each do |volume| %>
      - name: <%= volume.name %>
        persistentVolumeClaim:
          claimName: <%= volume.name %>
      <% end %>
      <% end %>