apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= name %>-deployment
  labels:
    app: <%= name %>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <%= name %>
  template:
    metadata:
      labels:
        app: <%= name %>
    spec:
      containers:
      - name: <%= name %>
        image: <%= container_registry_url %>
        imagePullPolicy: Always
        env:
        <% environment_variables.each do |env| %>
          - name: <%= env.name %>
            value: <%= env.value %>
        <% end %>
        ports:
        - containerPort: <%= port %>
        <% if service_command %>
        command: <% service_command.split(' ').each do |c| %>
          - <%= c %>
        <% end %>
        <% end %>
      imagePullSecrets:
      - name: dockerconfigjson-github-com
