apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: <%= name %>
  namespace: <%= project.namespace %>
  labels:
    caninemanaged: 'true'
spec:
  gatewayClassName: traefik
  listeners:
  <% service.domains.each_with_index do |domain, index| %>
  - name: https-<%= index %>
    protocol: HTTPS
    port: 443
    hostname: <%= domain.domain_name %>
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: <%= certificate_name %>
    allowedRoutes:
      namespaces:
        from: Same
  <% end %>
