apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: <%= name %>
  namespace: <%= project.namespace %>
  labels:
    caninemanaged: 'true'
spec:
  parentRefs:
  - name: <%= gateway_name %>
  hostnames:
  <% service.domains.each do |domain| %>
  - <%= domain.domain_name %>
  <% end %>
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: <%= service.name %>-service
      port: 80
