apiVersion: v1
kind: ResourceQuota
metadata:
  name: <%= constrainable.name %>-quota
  namespace: <%= constrainable.name %>
  labels:
    caninemanaged: 'true'
spec:
  hard:
    <% resource_constraint = constrainable.resource_constraint %>
    <% if resource_constraint.present? %>
    <% if resource_constraint.cpu_request.present? %>
    requests.cpu: "<%= resource_constraint.cpu_request_formatted %>"
    <% end %>
    <% if resource_constraint.cpu_limit.present? %>
    limits.cpu: "<%= resource_constraint.cpu_limit_formatted %>"
    <% end %>
    <% if resource_constraint.memory_request.present? %>
    requests.memory: "<%= resource_constraint.memory_request_formatted %>"
    <% end %>
    <% if resource_constraint.memory_limit.present? %>
    limits.memory: "<%= resource_constraint.memory_limit_formatted %>"
    <% end %>
    <% if resource_constraint.gpu_request.present? && resource_constraint.gpu_request > 0 %>
    requests.nvidia.com/gpu: "<%= resource_constraint.gpu_request %>"
    <% end %>
    <% end %>
