{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canine.fullname" . }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if index .Values "cert-manager" "enabled" }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: canine-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "canine.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
