apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canine.fullname" . }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.canine.secretKeyBase | b64enc | quote }}