{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "canine.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canine.fullname" . }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret (not .Values.canine.secretKeyBase) }}
  secret-key-base: {{ index $existingSecret.data "secret-key-base" }}
  {{- else if .Values.canine.secretKeyBase }}
  secret-key-base: {{ .Values.canine.secretKeyBase | b64enc | quote }}
  {{- else }}
  secret-key-base: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if and $existingSecret (hasKey $existingSecret.data "encryption-primary-key") }}
  encryption-primary-key: {{ index $existingSecret.data "encryption-primary-key" }}
  encryption-deterministic-key: {{ index $existingSecret.data "encryption-deterministic-key" }}
  encryption-key-derivation-salt: {{ index $existingSecret.data "encryption-key-derivation-salt" }}
  {{- else }}
  encryption-primary-key: {{ randAlphaNum 32 | b64enc | quote }}
  encryption-deterministic-key: {{ randAlphaNum 32 | b64enc | quote }}
  encryption-key-derivation-salt: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}