apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canine.fullname" . }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
type: Opaque
data:
  canine-username: {{ .Values.canine.auth.username | b64enc | quote }}
  canine-password: {{ .Values.canine.auth.password | b64enc | quote }}
  secret-key-base: {{ .Values.canine.secretKeyBase | b64enc | quote }}