{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "canine.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canine.fullname" . }}
  labels:
    {{- include "canine.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret (not .Values.canine.secretKeyBase) }}
  secret-key-base: {{ index $existingSecret.data "secret-key-base" }}
  {{- else if .Values.canine.secretKeyBase }}
  secret-key-base: {{ .Values.canine.secretKeyBase | b64enc | quote }}
  {{- else }}
  secret-key-base: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}